# Конфигурация агента аналитика для составления анализа задач и плана работ
agent:
  # Имя агента
  name: "Documentation agent"

  # Описание функций агента
  description: "Agent for analyze code and generate documentation"

  # Модель, которая должна использоваться агентом
  model: "qwen3.5:9b"

  # Путь до системного промпта в папке ресурсов проекта
  system_prompt: "config/agents/docs/system_prompt.md"

  # Набор инструментов, который доступен агенту
  toolset: [
    "search_files", "read_text_file", "write_text_file"
  ]
