tool:
  alias: "overwrite_text_file"
  name: "Overwrite text file"
  description: "Изменить содержимое текстового файла. Полностью перезаписывает 
  старые данные теми, что переданы в параметрах вызова. Запись произойдёт 
  через Files.write(Paths.get(filePath), newContent.getBytes())"
  parameters:
    - parameter:
        name: "filePath"
        type: "string"
        description: "Абсолютный путь к файлу в формате системы"
    - parameter:
        name: "newContent"
        type: "string"
        description: "Новые данные, которыми будет перезаписан файл."
  method: "ru.vych.tools.FileTools#overwriteFile"