# Конфигурация агента аналитика для составления анализа задач и плана работ
agent:
  # Имя агента
  name: "Analyst agent"

  # Описание функций агента
  description: "Agent analyst capabilities"

  # Модель, которая должна использоваться агентом
  model: "qwen3.5:4b"

  # Путь до системного промпта в папке ресурсов проекта
  system_prompt: "config/agents/analyst/system_prompt.md"

  # Набор инструментов, который доступен агенту
  toolset: [
    "search_files", "read_text_file", "write_text_file",
    "create_directory", "system_info"
  ]
