# Конфигурация агента промпт-инженера
agent:
  # Имя агента
  name: "Prompt engineering agent"

  # Описание функций агента
  description: "Agent for creating prompts"

  # Модель, которая должна использоваться агентом
  model: "qwen3.5:4b"

  # Путь до системного промпта в папке ресурсов проекта
  system_prompt: "config/agents/prompter/system_prompt.md"

  # Набор инструментов, который доступен агенту
  toolset: [
    "search_files", "read_text_file", "write_text_file",
    "web_search", "fetch_page", "system_info"
  ]
